[package]
name = "axplat-aarch64-rk3588"
version = "0.2.0"
description = "Implementation of `axplat` hardware abstraction layer for Rockchip RK3588."
documentation = "https://docs.rs/axplat-aarch64-rk3588"
keywords = ["arceos", "os", "hal", "embedded", "aarch64"]
categories = ["embedded", "no-std", "hardware-support", "os"]
authors = ["Yuekai Jia <equation618@gmail.com>", "Youjie Zheng <Azure_stars@126.com>", "Luoyuan Xiao <xiaoluoyuan@163.com>"]
edition = "2024"
license = "GPL-2.0"
repository = "https://github.com/elliott10/axplat-aarch64-rk3588"

[features]
fp-simd = ["axcpu/fp-simd"]
rtc = []
irq = ["axplat/irq", "axplat-aarch64-peripherals/irq", "gicv3"]
gicv3 = ["axplat-aarch64-peripherals/gicv3"]
smp = ["axplat/smp", "kspin/smp"]

[dependencies]
log = "0.4"
kspin = "0.1"
page_table_entry = "0.5"
axconfig-macros = "0.2"
axcpu = { version = "0.3", git = "https://github.com/arceos-org/axcpu.git", tag = "dev-v03" }
axplat = { git = "https://github.com/elliott10/axplat_crates.git", rev = "0ea84c51" }
axplat-aarch64-peripherals = { git = "https://github.com/elliott10/axplat_crates.git", rev = "0ea84c51" }

dw_apb_uart = { git = "https://github.com/elliott10/dw_apb_uart.git", rev = "9de1bf0f", features = ["board_rk3588"] }

[package.metadata.docs.rs]
targets = ["aarch64-unknown-none"]
